title   Arch Linux (%ARCH%, UEFI)
linux   /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd  /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% cow_spacesize=4G copytoram=y
