[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = https://mirrors.ztchary.net/archlinux/$repo/os/$arch

[extra]
Server = https://mirrors.ztchary.net/archlinux/$repo/os/$arch

[multilib]
Server = https://mirrors.ztchary.net/archlinux/$repo/os/$arch

